apartment_application_service/notifications.py
application_form/api/serializers.py
application_form/api/views.py
application_form/models.py
connections/utils.py

Add some assisting comments for the code.
Refs -

Add comments

---

requirements.txt

updates sugested by Dependabot

Update dependencies requirements.txt with security

---

connections/oikotie/field_mapper.py
connections/oikotie/oikotie_mapper.py
connections/tests/factories.py

Add Oikotie new development status mappings for elastic item to correspond existing enums

ASU-695 Fix new development status mapping

---

connections/api/rpc_views.py
connections/etuovi/services.py
connections/management/commands/send_etuovi_xml_file.py
connections/management/commands/send_oikotie_xml_file.py
connections/oikotie/services.py

Create django command for generating and sending XML files via FTP to Etuovi and Oikotie.
Delete XML file generating apis from rpc_views as not needed anymore but leave the class in place as it will be needed soon.

Asu 547 django commands for oikotie and etuovi data transfer

---

connections/etuovi/etuovi_mapper.py
connections/oikotie/oikotie_mapper.py

Add Helsinki appartment office presentation link to apartment at the end
of Oikotie and Etuovi apartment description text.

ASU-703 Add apartment presentation link

---

apartment_application_service/urls.py
users/admin.py
users/api/serializers.py
users/api/views.py
users/models.py
users/tests/test_api.py
users/urls.py

This PR adds the ability to create, retrieve, update, and delete profiles and users via a REST API.
The API does not yet require authentication via JWT. This will be added in a separate PR.

ASU-565 Add REST API for user/profile CRUD operations

---

.prod/on_deploy.sh
.prod/uwsgi.ini
Dockerfile
apartment_application_service/settings.py

There were some of the production configurations already done to this
repository so this finalizing the initial configuration for production
environments.
The code bases to Open City Profile's implementations:
https://github.com/City-of-Helsinki/open-city-profile

ASU-765 Finalize initial conf for production

---

azure-pipelines-master.yml

Changed to match release workflow on the project. After this change all
the code changes to develop branch will be triggered to dev and test
environment.

ASU-796 Change azure pipeline trigger to develop

---

connections/oikotie/oikotie_mapper.py
connections/tests/factories.py
connections/tests/test_oikotie.py

Add optional apartment description text if only apartment presentation
link is present. Add test.
Remove use of link to application as it is not wanted feature for now.
Add check for project_housing_company as it's mandatory field. Add test.

ASU-435 Update oikotie mapping

---

connections/etuovi/services.py
connections/management/commands/send_etuovi_xml_file.py
connections/management/commands/send_oikotie_xml_file.py
connections/oikotie/oikotie_mapper.py
connections/oikotie/services.py
connections/tests/test_etuovi.py
connections/tests/test_oikotie.py
requirements.in
requirements.txt

Updated oikotie and etuovi services functions to take in use variable
for path to xml folder.
Also django-oikotie and django-etuovi libraries are updated and this
change has been taken in use here.

Update oikotie and etuovi files creation function

---

connections/etuovi/services.py
connections/management/commands/send_oikotie_xml_file.py
connections/oikotie/services.py

This PR adds check for empty file as django-oikotie library cannot accept empty file for sending to FTP server.
Also improving logging for apartment mapping.

Add check for empty file

---

connections/elastic_models.py
connections/etuovi/etuovi_mapper.py
connections/oikotie/oikotie_mapper.py

Floor plan image is added to elastic apartment data and is now mapped
for Oikotie and Etuovi.
Updated elastic apartment test factory.

ASU-874 Add mapping for floor plan image

---

apartment_application_service/settings.py
utils/apps.py
utils/management/commands/clean_stress_test_data.py
utils/tests/test_clean_stress_test_data.py

This command cleans all the test data that will be created on the stress
test.

Add stress test clean command

---

.github/workflows/main.yml
apartment/elastic/documents.py
apartment/tests/conftest.py
apartment/tests/factories.py
application_form/tests/conftest.py
application_form/tests/factories.py
connections/etuovi/services.py
connections/oikotie/oikotie_mapper.py
connections/service/elastic.py
connections/tests/conftest.py
connections/tests/factories.py
connections/tests/test_etuovi.py
connections/tests/test_oikotie.py
connections/tests/test_service_elastic.py
connections/tests/utils.py
requirements-dev.txt
users/tests/factories.py

The tests had issues that the tests passed and failed very randomly in apartments. These changes stables the tests and so far on the 3 times in the row, these haven't failed anymore.

Refactor more apartment tests

---

application_form/api/serializers.py
application_form/api/views.py
application_form/exceptions.py
application_form/services/lottery/hitas.py
application_form/tests/test_lottery_api.py
application_form/urls.py
users/tests/factories.py

Adds API endpoint for lottery execution. The permissions check has not been added as the sales tool does not have authentication to Django.

Add API endpoint for lottery execution

---

connections/oikotie/oikotie_mapper.py

getattr-functions returned zero values as a None value and the tests
failed randomly because on test the value can be zero on fields
(conftest).

fix: oikotie mapper not handle 0 values correctly

---

apartment/api/serializers.py
apartment/tests/api/test_views.py

A project's `lottery_completed` will be `True` if there exists at least one `LotteryEvent` for any of the project's apartments.

ASU-1327 | Add lottery_completed boolean field to project API data

---

customer/api/sales/serializers.py
customer/tests/api/sales/test_customer_api.py

Added `ApartmentReservation`s and `ApartmentInstallment`s inside them to `Customer` detail endpoint API data.
Example response:
```json
{
"id": 3,
"additional_information": "",
"created_at": "2022-02-11T11:40:24.913175+02:00",
"has_children": null,
"has_hitas_ownership": null,
"is_age_over_55": null,
"is_right_of_occupancy_housing_changer": null,
"last_contact_date": null,
"primary_profile": {
"id": "e559e6be-e824-4769-b55e-ce0c2d572933",
"first_name": "Matti",
"last_name": "Mainio",
"email": "matti@example.com",
"phone_number": "2435234",
"national_identification_number": null,
"street_address": "Jokutie 5 D",
"postal_code": "24523",
"city": "Helsinki",
"contact_language": "fi"
},
"right_of_residence": null,
"secondary_profile": {
"id": "774860ac-8192-454b-95d1-27dfd29d492c", …
```

ASU-1324 | Add reservations and installments to customer detail API data

---

apartment_application_service/utils.py
customer/api/sales/serializers.py
customer/api/sales/views.py
customer/tests/api/sales/test_customer_api.py
customer/tests/conftest.py
users/api/sales/serializers.py
users/tests/utils.py

Implemented APIs for creating and updating customers. New `Profile`s are created for every new `Customer`, ie. it is not possible to select an already existing `Profile` when creating a new `Customer`. Also, when updating a `Customer`, the related `Profile`s are updated, and it is not possible to change the `Profile`s to other `Profile`s.
Partial update (HTTP PATCH) is disabled for now, because it would make the update logic more complicated, and it is still unclear whether it is actually needed or not.
POST /v1/sales/customers/
```json
{
"additional_information": "",
"created_at": "2022-02-11T11:40:24.913175+02:00",
"has_children": true,
"has_hitas_ownership": null,
"is_age_over_55": null,
"is_right_of_occupancy_housing_changer": null,
"last_contact_date": null,
"primary_profile": { …
```

ASU-130 | Customer create and update API

---

customer/api/sales/views.py
customer/tests/api/sales/test_customer_api.py
customer/tests/utils.py

The customer list is now able to filter by the search terms. The search requires at least two char to execute the search.

feat: add customer list filters

---

apartment/api/sales/serializers.py
apartment/tests/api/test_views.py
application_form/api/sales/serializers.py

* add apartment url to project data in endpoint
* remove snn from project data in endpoint
* add email to applicant data in endpoint
* add customer id to apartment reservation

ASU-1283 | Changes to apartment reservation endpoint

---

apartment/tests/api/test_views.py
application_form/api/sales/serializers.py

Get has_children value from Customer if no application available, fix serializer so it'll return null value if no application attached to the reservation

ASU-1358 | Get has_children value from customer if no application available

---

application_form/api/serializers.py
application_form/services/reservation.py
application_form/tests/api/test_apartment_reservation_api.py
customer/api/sales/serializers.py
customer/tests/api/sales/test_customer_api.py

Misc fixes/improvements related to Reservation API.

Reservation API fixes

---

application_form/services/export.py
application_form/tests/test_export_service.py

Update CSV template to show both applicants in a same CSV row

Update csv template

---

apartment_application_service/pdf.py

When a multi-page PDF has fields with the same name, no matter what is the actual value of the field, the PDF viewer will display all fields using the same value, it's either the first value or the last value depending on the PDF viewer application.
To fix that we need to append a random suffix value to the field name of every page so that the PDF viewer can show the correct field values.

ASU-1459 | Fix multiple pdf display same values

---

apartment/api/views.py
apartment/tests/api/test_views.py
apartment/urls.py
application_form/services/export.py
application_form/tests/test_export_service.py

Add lottery result CSV export service
Refactor the export service class to be reusable

ASU-1391 | Refactor export service, add lottery result export service

---

apartment/api/sales/serializers.py
apartment/api/views.py
apartment/elastic/queries.py
apartment/tests/api/test_views.py
apartment/tests/factories.py
apartment/urls.py
apartment/utils.py
application_form/services/export.py
application_form/tests/test_export_service.py

ASU-1292 | Add export sale report service

---

application_form/enums.py
application_form/services/offer.py
application_form/tests/api/test_offer_api.py

Cancel all other reservations of a customer in the same project when giving an offer to that customer.
Cancellation reason/comment should be "Offered {apartment_number"

ASU-1239 | Cancel other customer's reservation in queue after sending an offer

---

apartment/services.py
application_form/tests/api/test_apartment_reservation_api.py

* changed "haso-vaihtaja" -> "Asumisoikeus asunnon vaihtaja"
* changed empty right of residence number and empty boolean values to
"Ei tiedossa" (unknown)
* added code that makes sure there is no more and no less than exactly
one empty line between intro, dynamic part and content

ASU-1522 | Offer message fine-tuning

---

application_form/models/reservation.py
application_form/services/application.py
application_form/tests/test_lottery_haso_services.py
application_form/tests/test_lottery_hitas_services.py

Details in the commit messages.

ASU-1468 | Fix reservation cancellation logic

---

apartment/api/serializers.py
apartment/tests/api/test_views.py

GET `/v1/sales/projects/<id>/`
```json
{
...
"lottery_completed_at": "2022-03-29T13:19:22.194296Z",
"application_count": 777
...
}

ASU-1476 | Add lottery_completed_at and application_count to project detail API endpoint

---

apartment/api/serializers.py
application_form/api/sales/serializers.py

Changed "has_multiple_winning_apartments" field in project detail API query reservation data to be resolved with DB annotations. The result requires fewer DB and Elastic Search queries than the original solution, and it performs quite a bit faster (1 sec vs 12 sec in one not very uncomprehensive test).

ASU-1541 | Make project detail API query faster

---

application_form/urls.py

This change has already been applied to the Sales UI [in here](https://github.com/City-of-Helsinki/att-sales-ui/commit/32c078e95db04b7d2b7f02841d7d77250bcbe7b9#diff-72a8c09a5db925b93d952f7fb0f76cff1c24d413ca3daa06e58b3568944b1d86R67).

ASU-1561 & ASU-1562 | Fix lottery execution API endpoint URL

---

apartment_application_service/settings.py
invoicing/management/commands/send_installments_to_sap.py
invoicing/services.py
invoicing/tests/test_commands.py
requirements-dev.in
requirements-dev.txt

- Add a simple email template
- Email will be sent right after the cron task sending installments to SAP
- Fixed a test related to marking sent installments
- Remove unused config for `django-mailer` which we are not using at the moment

ASU-1429 | Email notification after sending installments to SAP

---

application_form/pdf/haso.py

Add aso number to HASO PDF, show full customer full address

ASU-1501 | Add aso number to HASO PDF, show full address

---

application_form/api/sales/serializers.py
application_form/api/serializers.py
application_form/enums.py
application_form/services/application.py
application_form/services/lottery/utils.py
application_form/services/offer.py
application_form/services/queue.py
application_form/services/reservation.py
application_form/tests/api/test_apartment_reservation_api.py
application_form/tests/test_application_api.py
application_form/tests/test_lottery_api.py
application_form/tests/test_lottery_haso_services.py
application_form/tests/test_lottery_hitas_services.py
application_form/tests/test_sales_application_api.py
customer/tests/api/sales/test_customer_api.py
invoicing/api/serializers.py
users/models.py

Reservation state change log improvements: 
- Added two new automatically populated cancel reasons LOWER_PRIORITY and OFFER_REJECTED
- Implemented Drupal-based salesperson populating which was missing before
Also changed metadata handler field to be populated from the user's profile if one is available, because Drupal-based users have their name and email there.

ASU-1590 | Reservation state change log improvements

---

apartment/api/serializers.py
apartment/tests/api/test_views.py

When the reservation is not a winning reservation, we don't want to show the bell icon in the sales UI

ASU-1581 | Fix customer_has_multiple_winning_apartments

---

application_form/api/sales/serializers.py
application_form/tests/api/test_apartment_reservation_api.py
invoicing/api/serializers.py
invoicing/tests/test_api.py

Support calculating value for flexible installments based on the sale price of the apartment.

Support flexible installments

---

application_form/services/queue.py
application_form/tests/test_queue_services.py

Encountered some test data in which active reservations had no from_position and as a result their termination was not possible.

Skip shift positions if from_position is None

---

cost_index/api/views.py
cost_index/tests/test_cost_index_api.py

Remove adjusted_right_of_occupancy_payment. Add
right_of_occupancy_payment_adjustment and release_payment fields. Also removed the recursive method for calculating total alteration work. alteration_work_total field name does not change, but now it reflects the exact value of the ApartmentRevaluation model. This change comes from customer requirement of preferring to use the alteration work field always to store the total alteration work done on the apartment.

Tweak index cost Drupal API

---

asko_import/admin.py
asko_import/describer.py
asko_import/importer.py
asko_import/management/commands/import_from_asko.py
asko_import/models.py

Fix reservation positions in AsKo import and include the object descriptions
to the Django Admin view of the AsKo import log entries.

asko_importer: Fix reservation positions and log improve (ASU-1430)

---

asko_import/admin.py
asko_import/describer.py
asko_import/importer.py
asko_import/issues.py
asko_import/models.py

Tune the AsKo importing so that we get correct owner (= reserver or buyer)
for every apartment.  Some of the status changes have been done in AsKo
without any reservations or lottery events so we have to create separate
reservations for those status update from the `apartment.txt`.
Also improve the Django Admin side so that it's easier to inspect
the import logs.  Namely, make customer names and apartment/project
names visible in more places.

asko_import: Import owner data from apartment.txt etc. (ASU-1430)

---

asko_import/importer.py
asko_import/management/commands/import_from_asko.py

Make the first position in the queue as reserved as this
was discussed in the review of the previous asko_import PR.
Also includes some related fixes and tooling improvements.

asko_import: Make 1st queue position reserved (ASU-1430)

---

README.md
apartment_application_service/settings.py
invoicing/sap/fetch/sftp.py
invoicing/services.py
invoicing/tests/conftest.py
invoicing/tests/test_commands.py

Adjust the SAP payment fetching code so that it can read also uppercase
filenames and use separate connection settings for the SFTP server
for fetching payments and sending invoices.
Additionally tune the logging calls a bit.

Modify SAP payment fetching (ASU-1467)

---

.github/workflows/main.yml

This should make the CI complete faster, since now many checks can be run in parallel.  It also allows seeing results of the individual checks more easily.

CI: Separate checks to their own jobs

---

application_form/services/queue.py
application_form/tests/test_queue_services.py

The previous fix on commit 72ad1913 wasn't enough, because the list position will still need adjusting even though the reservation is cancelled.  This is because (apartment_uuid, list_position) is a unique key in the database and if we don't adjust the list positions there will be a duplicate key.
Fix the issue by making the code to adjust both the queue positions and the list positions.
Additionally, fix the _calculate_queue_position function so that it won't read the queue positions of the cancelled reservations, because they are None and mess up the calculations.
Also add a test case to make sure that this fix works better.

Fix adding application to queue with cancelled reservations

---

apartment/elastic/documents.py
apartment/tests/factories.py

Also reorder the field contents in the project_contract_combined_terms field.

Fix field name: project_contract_customer_document_handover

---

.github/workflows/main.yml
README.md

Temporary solution to a bug in pip version >= 24.3
https://github.com/jazzband/pip-tools/issues/2131

Pin pip version to 24.2

---

.github/workflows/main.yml
apartment/api/views.py
apartment/urls.py
application_form/services/export.py
application_form/tests/test_export_service.py

* Add new export service for project applicants mailing list
* Add tests for new export service

 Add endpoint for downloading a project applicants mailing list

---

application_form/services/export.py
application_form/tests/conftest.py
application_form/tests/test_export_service.py

Sort ApplicantMailingListExportService CSV by apartment_number and not apartment_uuid

---

customer/api/sales/serializers.py

Frontend changes at: https://github.com/City-of-Helsinki/att-sales-ui/pull/136

Add right of residence number (asumisoikeusnumero) to customer list serializer

---

application_form/tests/api/test_apartment_reservation_api.py
invoicing/api/serializers.py
invoicing/enums.py
invoicing/sap/send/xml_utils.py
invoicing/tests/test_api.py

Frontend changes at https://github.com/City-of-Helsinki/att-sales-ui/pull/148

Rename InstallmentTypes.REFUND_1 -> REFUND

---

application_form/pdf/haso.py
application_form/tests/api/test_apartment_reservation_api.py
invoicing/enums.py
invoicing/sap/send/xml_utils.py
invoicing/tests/test_api.py

Related frontend PR https://github.com/City-of-Helsinki/att-sales-ui/pull/152

RIGHT_OF_OCCUPANCY_PAYMENT_1 to RIGHT_OF_OCCUPANCY_PAYMENT

---

apartment/elastic/documents.py
apartment/tests/factories.py
connections/etuovi/etuovi_mapper.py
connections/tests/factories.py
connections/tests/test_etuovi.py

- Add project_completion_date as a field to ApartmentDocument
related PR on Drupal side 
https://github.com/City-of-Helsinki/drupal-asuntotuotanto/pull/716

Use `release_payment` instead of `debt_free_sales_price` in Etuovi export if apartment is HASO apartment

---

application_form/services/export.py
application_form/tests/test_export_service.py

"Project address" --> "Kohteen osoite"
"Apartments total" --> "Asuntoja yhteensä"
"Sold HITAS apartments" --> "Myydyt HITAS-asunnot"
"Sold HASO apartments" --> "Myydyt HASO-asunnot"
"Unsold apartments" --> "Myymättömät asunnot"

Change language of headers in XlsxSalesReportExportService to Finnish

---

.github/workflows/main.yml
invoicing/sap/send/xml_utils.py

Cherrypick commit 467a54a to fix xml utils

Cherrypick commit 467a54a to fix xml utils

---

application_form/services/export.py
application_form/tests/test_export_service.py

- Fix sales report crashing if ApartmentReservationStateChangeEvent wasnt found for apartment included in the report

Sales report hotfix

---

application_form/services/export.py
application_form/tests/test_export_service.py

Change how sold apartments displayed on sales report is counted

Asu 1711 missing sold events

---

apartment/api/views.py

- include the end day of the given date range into search for ApartmentReservationStateChangeEvents

Tweak date selection in salesreport

---

application_form/services/export.py
application_form/tests/test_export_service.py

- **Refactor, improve tests, change how total unsold at bottom line is calculated**
- **Format, fix lint err**

Refactor, improve tests, change how total unsold at bottom line is calculated

---

application_form/tests/test_export_service.py

- Fix flaky test `test_export_applicants_mailing_list_first_in_queue`

ASU-1737: Fix tests
