City-of-Helsinki/apartment-application-service

- apartment_application_service/apps.py
- apartment_application_service/consts.py
- apartment_application_service/notifications.py
- apartment_application_service/settings.py
- requirements.in
- requirements.txt
Add inintial integration of django-ilmoitin 0.5 to the project.
From django-ilmoitin readme: "Use version 0.5.x for a project based
on Django 2.x".
ASU-222 | Integrate django-ilmoitin
> Add django-ilmoitin

- connections/tests/test_etuovi_mapper.py
Update the django-etuovi mapper typing test to be imported from the django-etuovi package. This way we don't have to maintain this code in two places.
> Update django-etuovi mapper typing test

- apartment_application_service/settings.py
Currently, there isn't a need to separate logging configurations per app
so previous configurations were reverted. The LOG_LEVEL environment
variable has been left that there is a possibility to manage the logging
level in the console.
> Revert logging settings

- apartment_application_service/openapi.py
- apartment_application_service/settings.py
- apartment_application_service/urls.py
- requirements-dev.txt
- requirements.in
- requirements.txt
This PR adds an [OpenAPI specification](https://swagger.io/specification/) and API documentation generation to the project, as recommended by [the documentation best practices](https://dev.hel.fi/documentation#api-documentation).
The OpenAPI spec is served at the `/openapi/` endpoint.
The API documentation can be viewed at:
* `/api_docs/` for Redoc UI
* `/api_docs/swagger/` for Swagger UI
See [ASU-712](https://helsinkisolutionoffice.atlassian.net/browse/ASU-712) for screenshots of the generated documentation.
The API spec and documentation are automatically generated by [drf-spectacular](https://github.com/tfranzel/drf-spectacular). By default, it does not generate very human-readable endpoint summaries and descriptions, so its `AutoSchema` has been extended to provide a bit more readable …
> ASU-712 Add OpenAPI specification and API documentation

- apartment_application_service/settings.py
Using `environ.Path` with `default_var_root` seemed to cause local Docker builds to fail with an error:
```
Traceback (most recent call last):
File "manage.py", line 23, in <module>
main()
File "manage.py", line 19, in main
execute_from_command_line(sys.argv)
File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
utility.execute()
File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 325, in execute
settings.INSTALLED_APPS
File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 79, in __getattr__
self._setup(name)
File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 66, in _setup
self._wrapped = Settings(settings_module)
File …
```
> Fix VAR_ROOT error when treated as a path

- .gitignore
- apartment_application_service/settings.py
- requirements.in
- requirements.txt
With a couple of lines of config WhiteNoise allows your web app to serve
its own static files, making it a self-contained unit that can be
deployed anywhere without relying on nginx, Amazon S3 or any other
external service. (Especially useful on Heroku, OpenShift and other PaaS
providers.)
Refs ASU-793
> ASU-793 Add whitenoise for OpenShift enviroments

- apartment_application_service/settings.py
- audit_log/audit_logging.py
- audit_log/enums.py
- audit_log/tests/conftest.py
- audit_log/tests/test_audit_logging.py
This PR adds a centralized audit logger which can be used to log audit events.
It is loosely based on Helsinki Open City Profile audit log system. Each audit event consists of the following data:
* Actor (user who performed the action)
* Operation (action that was performed, e.g. "CREATE", "READ", "UPDATE", "DELETE")
* Target (ID and type of the model instance which was the target of the operation, e.g. "Profile" or "Application")
* Status (whether the operation was successful, e.g. "SUCCESS", "FORBIDDEN")
* Timestamp
The audit logs are stored in the file specified by `AUDIT_LOG_FILENAME` or printed to console if no file is specified.
Each audit entry is a JSON-formatted string on a single line, e.g.:
```json
{"audit_event": {"origin": "APARTMENT_APPLICATION_SERVICE", "status": "SUCCESS", …
```
> ASU-816 Add centralized audit logger

- audit_log/audit_logging.py
- audit_log/enums.py
- audit_log/tests/conftest.py
- audit_log/tests/test_audit_logging.py
- users/api/permissions.py
- users/api/views.py
- users/tests/test_api.py
This PR adds audit logging for all CRUD operations for user profiles.
Each audit log entry has an *actor*, *operation*, and *target*.
* The actor is the authenticated user profile.
* The only exception to this is creating a new profile -- since no user can be authenticated before the profile is created, the user is anonymous.
* The action is either `CREATE`, `READ`, `UPDATE`, or `DELETE` depending on the HTTP method.
* The target is the user profile.
> ASU-818 Add audit logging for user profile operations

- apartment_application_service/models.py
- application_form/models.py
- users/models.py
This PR adds an abstract `TimestampedModel` that provides `created_at` and `updated_at` fields.
The models that have these fields have been updated to inherit from this class.
No migrations are needed since the affected models already included these fields.
> Add abstract timestamped model

- application_form/api/views.py
- application_form/models.py
- application_form/tests/conftest.py
- application_form/tests/test_application_api.py
- audit_log/audit_logging.py
- audit_log/tests/utils.py
- audit_log/viewsets.py
- users/api/views.py
- users/tests/test_api.py
This PR adds audit logging for applications.
Since there are now two viewsets where audit logging is used (profiles and applications), I extracted the audit logging logic into its own viewset that can be inherited. The new viewset automatically writes audit log events for all CRUD operations related to that view. This viewset is now used by both profile and application views.
> ASU-819 Add audit logging for applications

- requirements.in
- requirements.txt
The development of Etuovi and Oikotie caused incompatibility in the
development as the specified version pointed into the develop branch
which is under development. This change is also MUST do that we'll be
using the release version in the future releases.
> Change Etuovi and Oikotie to use releases

- connections/management/commands/send_oikotie_xml_file.py
- connections/tests/test_oikotie.py
Oikotie accepts housing companies and apartments xml-files transfering
with 10 min delay between them. Updated command with flag to send either
one file.
> ASU-878 Add option for sending files separately

- connections/etuovi/services.py
- connections/management/commands/send_etuovi_xml_file.py
- connections/oikotie/services.py
- connections/tests/conftest.py
- connections/tests/factories.py
- connections/tests/test_api.py
- connections/tests/test_etuovi.py
- connections/tests/test_oikotie.py
- connections/tests/utils.py
This PR adds option to extract apartments from elastic data by flags published_on_oikotie and published_on_etuovi.
Test data generation for elasticsearch has been modified to better address Oikotie and Etuovi fetching separation. Test utils has been added for different testing purposes. Some improving was done overall for testing utils.
> ASU-859 Add option to choose vendor for transfer

- apartment_application_service/settings.py
This PR fixes a minor issue with logging. Currently some log messages are duplicated in the logs:
```
2021-08-04 09:25:36,961 p29464 django.request WARNING: Unauthorized: /v1/profiles/
2021-08-04 09:25:36,961 p29464 django.request WARNING: Unauthorized: /v1/profiles/
2021-08-04 09:25:36,961 p29464 django.server WARNING: "GET /v1/profiles/ HTTP/1.1" 401 16074
2021-08-04 09:25:36,961 p29464 django.server WARNING: "GET /v1/profiles/ HTTP/1.1" 401 16074
```
This happens because the `django` logger is missing `"propagate": False`, which causes the root logger (`""`) to re-print the logs, doubling the log size.
The fix is to add `"propagate": False` to the logger. This fixes the log output:
```
2021-08-04 09:26:06,262 p29480 django.request WARNING: Unauthorized: /v1/profiles/
2021-08-04 …
```
> ASU-365 Fix duplicate logging

- audit_log/admin.py
Pygments is listed only in development dependencies, so we can't use it (CI build will fail).
This PR fixes the problem by formatting the messages with `<pre>` tags. There is no syntax highlighting, but the audit log message is still easier to read compared to no formatting.
> ASU-935 Format audit log message without Pygments

- application_form/services.py
- application_form/tests/test_services.py
This PR fixes a bug with creating applications. I found this bug while developing our load testing script.
If a project or an apartment has already appeared in some previous application, creating a new application with the same project or apartment may fail with an integrity error:
```
IntegrityError
duplicate key value violates unique constraint "apartment_identifier_schema_type_identifier_72712817_uniq"
DETAIL:  Key (schema_type, identifier)=(att_pro_es, c50c112d-c14a-4768-a2ce-c76b0e19456e) already exists.
```
The problem is in `create_application`, which uses Django's `get_or_create` slightly wrong way. The code was trying to create a new record for project and apartment identifiers every time, even if an identifier for the project or apartment may already exist in the database.
I …
> ASU-919 Fix integrity error if identifier already exists

- .env.example
- apartment_application_service/settings.py
Starting a fresh development environment currently fails due to missing email schema. This PR fixes that as well as sets the email configuration to be explicit instead of relying or django-environ _hopefully_ settings variables.
> Explicit email configuration

- apartment_application_service/urls.py
- audit_log/api/serializers.py
- audit_log/api/views.py
- audit_log/tests/api/test_serializers.py
- audit_log/tests/api/test_views.py
- audit_log/tests/conftest.py
- audit_log/urls.py
Adds simple CREATE method to Audit Log API that the external application can add audit logs to Django which currently centralizes audit logs.
> Add auditlog view

- apartment_application_service/settings.py
Django 3.2 requires that the default AutoField is defined to settings,
otherwise, it provides a warning message.
By default, Django generates the new projects to use BigAutoField so in
this we follow the same thing.
> Add default AutoField to Settings

- apartment/api/serializers.py
- apartment/api/views.py
- apartment/elastic/documents.py
- apartment/elastic/queries.py
- apartment/tests/api/test_views.py
- apartment/tests/conftest.py
- apartment/tests/factories.py
- apartment/urls.py
- apartment_application_service/urls.py
- connections/etuovi/etuovi_mapper.py
- connections/oikotie/oikotie_mapper.py
- connections/service/elastic.py
- connections/tests/factories.py
- connections/tests/test_apartment_model.py
- connections/tests/test_etuovi.py
- connections/tests/test_oikotie.py
- connections/tests/test_service_elastic.py
This adds a project list API endpoint for the sales tool. It retrieves the project data only from the ElasticSearch and mapping the fields for the project item.
Here has also made a bit of refactoring. The ApartmentDocument will be now on the Apartment application which is one of the base applications in the system.
> Add project list API endpoint to Apartment application

- apartment/api/serializers.py
- apartment/api/views.py
- apartment/elastic/documents.py
- apartment/elastic/queries.py
- apartment/tests/api/test_views.py
- apartment/tests/factories.py
* Change ProjectAPIView to use APIView parent (similarly in ApartmentAPIView)
* Remove authentication from the ProjectAPIView (permissions check will be added later when the authentication works)
* Get all the project data from elasticsearch. Currently, it returns only 10 items.
* Add API endpoint to get a single project item
* Use the filter in Apartment and Project search
* Add missing project_state_of_sale field to Project document and endpoint.
> Improve the project API view

- apartment/api/views.py
- apartment/tests/api/test_views.py
- apartment/urls.py
* If the API is called with the project_uuid parameter, then return
the single item.
* Add project_uuid to URL parameters in project API
> Return single item instead array in Project API

- .sonarcloud.properties
- apartment/tests/conftest.py
- apartment/tests/factories.py
- application_form/api/serializers.py
- application_form/services/lottery/hitas.py
- application_form/tests/conftest.py
- application_form/tests/test_application_api.py
- application_form/tests/test_application_services.py
- application_form/tests/test_sales_application_api.py
- application_form/tests/utils.py
- connections/etuovi/services.py
- connections/oikotie/services.py
- connections/service/elastic.py
- connections/tests/conftest.py
- connections/tests/factories.py
- connections/tests/test_api.py
- connections/tests/test_etuovi.py
- connections/tests/test_oikotie.py
- connections/tests/utils.py
* Refactor, simplify and fix the usage of elasticsearch in tests
* Add SonarCloud properties file which excludes paths and set the use of python 3
* And fixed other issues what has appeared on the fixing and refactoring
This is now 5 times attempted on the CI test without any errors.
> Test: Refactor, simplify and fix the unit tests

- apartment/tests/factories.py
- application_form/api/serializers.py
- application_form/api/views.py
- application_form/tests/api/test_project_reservation_view.py
- application_form/tests/factories.py
- application_form/urls.py
This endpoint is made for a user profile that returns the user's apartment reservations of a project they have applied for.
The URL path is `profiles/me/projects/<uuid:project_uuid>/reservations`. The information of the user profile has been separated under the `profiles`.
The API is inherited from the `GenericAPIView` that we get also the response information to Swagger.
> Add project's apartment reservation list endpoint

- application_form/services/lottery/hitas.py
- application_form/services/lottery/machine.py
- application_form/tests/test_lottery_api.py
* Move the checkup of the application count that it also covers HASO apartments. Before the lottery can be executed, the project needs to have applications.
* Add HASO tests for the lottery API endpoint
> Improve HASO in lottery API endpoint

- application_form/api/sales/views.py
Disabled authentication altogether from the execute lottery API endpoint for now. Authentication isn't actually used at the moment so this change doesn't actually change anything, but it is needed so that the endpoint won't return a CSRF error.
> Fix execute lottery API endpoint temporal CSRF issue

- application_form/api/sales/serializers.py
- application_form/api/serializers.py
- application_form/tests/test_sales_application_api.py
Disabled SSN suffix validation from the sales API application endpoint. The validation is still present on the non-sales application endpoint.
The two application endpoints used serializers in a manner that made it difficult to disable the validation from just the sales one, so did also some refactoring to make it easier to customize them separately; previously `SalesApplicationSerializer` inherited directly from `ApplicationSerializer`, now they both inherit from a common base class, which contains all the common functionality.
> ASU-1262 | Disable sales application API ssn suffix validation

- application_form/api/sales/views.py
- application_form/services/lottery/exceptions.py
- application_form/services/lottery/haso.py
- application_form/services/lottery/hitas.py
- application_form/services/lottery/machine.py
- application_form/services/lottery/utils.py
- application_form/tests/conftest.py
- application_form/tests/test_lottery_api.py
- application_form/tests/test_lottery_haso_services.py
- application_form/tests/test_lottery_hitas_services.py
This add application time validation to lottery execution. The lottery can be executed only after the project's application time has finished.
> Add project application time validation to lottery

- apartment/api/serializers.py
Before this fix the apartment list in the project detail API endpoint included all the apartments there are in the db, now it correctly includes only the apartments of the project.
> Fix project detail API endpoint apartment list

- apartment/elastic/queries.py
- application_form/api/sales/serializers.py
- application_form/api/serializers.py
- application_form/api/views.py
- application_form/tests/api/test_apartment_reservation_api.py
- application_form/urls.py
- invoicing/api/serializers.py
- invoicing/models.py
- invoicing/tests/test_api.py
- invoicing/utils.py
Implemented API which makes it possible to create apartment installments from project installment templates. This needs a reservation detail endpoint, so that is first created to URL `/v1/sales/apartment_reservations/<reservation id>/`.
When creating apartment installments, one needs to first get installment candidates for the reservation from the reservation detail endpoint, and then use those with or without changes to actually create the apartment installments (via `/v1/sales/apartment_reservations/<reservation id>/installments/`).
Added also initial dummy implementation for generating installment reference numbers.
> ASU-1287 | API for generating apartment installments from installment templates

- customer/models.py
- customer/tests/test_customer_models.py
Simplified Customer profiles' validation a bit and changed clean() to be called on save() for consistency reasons. At the same time, a bug in the validation that prevented single profile Customers to be created on some occasions got fixed.
> Embetter Customer Profile validation

- apartment/api/sales/serializers.py
- application_form/api/sales/serializers.py
- application_form/api/serializers.py
- application_form/tests/api/test_apartment_reservation_api.py
- application_form/tests/api/test_project_reservation_view.py
- customer/tests/api/sales/test_customer_api.py
- Hide queue position if lottery hasn't been executed yet
- Rename ApartmentReservationSerializer to SaleApartmentSerializer ( there were two ApartmentReservationSerializer classes)
> ASU-1378 | Hide queue position when lottery hasn't been executed yet

- apartment/api/sales/serializers.py
- apartment/enums.py
- apartment/tests/api/test_views.py
- apartment/tests/conftest.py
Added `state` field to the apartment data in the sales API project detail endpoint. The value will be determined from the current winning reservation of the apartment. Before the apartment's lottery, the value will be always `free`.
> ASU-1346 | Add apartment state

- apartment/elastic/queries.py
- application_form/api/sales/serializers.py
- application_form/api/sales/views.py
- application_form/api/serializers.py
- application_form/services/reservation.py
- application_form/tests/api/test_apartment_reservation_api.py
- application_form/utils.py
Implemented ApartmentReservation creation functionality to ApartmentReservationViewSet. It is used by issuing a POST request to URL /v1/sales/apartment_reservations/.
Reservations can be added at the end of the apartment's reservation queue. If there are no existing reservations in the queue, the newly created reservation will get state RESERVED, otherwise it will get state SUBMITTED.
**HTTP POST /v1/sales/aparment_reservations/**
```json
{
"apartment_uuid": "1623bb70-74c0-44a5-b96b-a3ccf96a05f6",
"customer_id": 3
}
```
**HTTP 201**
```json
{
"installments": [],
"installment_candidates": [],
"customer_id": 3,
"id": 28,
"apartment_uuid": "1623bb70-74c0-44a5-b96b-a3ccf96a05f6",
"list_position": 11,
"queue_position": 11,
"priority_number": null,
"state": "submitted"
}
```
> ASU-1332 | Add ApartmentReservation create API

- apartment/tests/api/test_views.py
- application_form/api/sales/serializers.py
- users/tests/utils.py
The sales UI requires this change to display customer information in reservation lists. Currently it uses "applicants" data, but that doesn't work for reservations without an application.
> ASU-1439 | Change customer ID to customer object in project detail API

- application_form/api/sales/serializers.py
Applicant data is not needed anymore in project detail API because the Sales UI uses customer data now instead.
> ASU-1455 | Remove applicants field from project detail API

- invoicing/api/serializers.py
Before this fix, ApartmentInstallment fields added_to_be_sent_to_sap_at and sent_to_sap_at were nullified when the apartment's installments where edited.
We need to prevent editing of certain installment rows in the future, which will probably require some refactoring to the whole installment edit API, so this fix is likely to be just a temporary one.
> Fix apartment installment SAP fields handling on API edit

- apartment/services.py
- application_form/api/sales/serializers.py
- application_form/api/sales/views.py
- application_form/tests/api/test_apartment_reservation_api.py
Added fields `recipients` and `subject` to the generated offer message and renamed the old field `message` to `body`.
Example response now:
```json
{
"subject": "Tarjous As Oy Pojanlohi C4",
"body": "Lorem ipsum\r\n\r\nHuoneisto: C4\r\nHuoneistotyyppi: 5h+k\r\n\r\nIpsum\r\nLorem\r\n",
"recipients": [
{
"name": "Ulla Taalasmaa",
"email": "ulla@example.com"
},
{
"name": "Suppo Taalasmaa",
"email": "suppo@example.com"
}
]
}
```
> ASU-1511 | Add recipients and subject to generated offer message data

- application_form/api/sales/serializers.py
- application_form/services/offer.py
- application_form/tests/api/test_offer_api.py
* make reservation read-only
* keep old `concluded_at` timestamp
> Fixes to offer update API

- apartment_application_service/settings.py
Added setting `OIDC_LEEWAY` with a value of 61 mins for `drf-oidc-auth`, because otherwise it will reject API tokens when they are older than the default value of 10 mins.
> Fix drf-oidc-auth rejecting API tokens older than 10min

- apartment/services.py
- application_form/api/sales/serializers.py
- application_form/api/sales/views.py
- application_form/api/serializers.py
- application_form/tests/api/test_apartment_reservation_api.py
Added valid_until date to the offer messages that can be generated for reservations. The value can be given in the offer message API request with query parameter valid_until=<YYYY-MM-DD>. If the parameter is not used, the value of the reservation's offer instance will be used if one exists.
This functionality is needed because the Sales UI needs to fetch offer messages with valid until dates also for reservations that do not have an existing offer yet.
> ASU-1519 | Add valid_until to offer messages

- application_form/api/serializers.py
- application_form/models/reservation.py
- application_form/tests/api/test_apartment_reservation_api.py
- customer/tests/api/sales/test_customer_api.py
Added `cancellation_reason` and `changed_by` to reservation state change history (`state_changes`) in customer detail endpoint.
GET `/v1/sales/customers/<id>/`
```json
{
...
"apartment_reservations": [
{
...
"state_change_events": [
{
"timestamp": "2022-06-13T11:56:36.222628+03:00",
"state": "reserved",
"comment": "",
"cancellation_reason": null,
"changed_by": null
},
{
"timestamp": "2022-06-13T11:58:54.383341+03:00",
"state": "canceled",
"comment": "",
"cancellation_reason": "canceled",
"changed_by": {
"id": 5,
"first_name": "Tuomas",
"last_name": "Haapala",
"email": "tuomas.haapala@anders.fi"
}
}
]
}
]
}
> ASU-1469 & ASU-1473 | Additions to customer detail endpoint reservation history

- apartment/tests/api/test_views.py
- apartment/tests/conftest.py
- application_form/services/reservation.py
- application_form/tests/api/test_apartment_reservation_api.py
- application_form/tests/api/test_offer_api.py
- application_form/tests/test_lottery_api.py
- customer/tests/api/sales/test_customer_api.py
- customer/tests/conftest.py
- invoicing/tests/conftest.py
- invoicing/tests/test_api.py
Fixed reservation transferring, which was broken because of a minor bug in reservation metadata handler field populating that managed to slip through when [that same thing was fixed for other parts of the system a while ago](https://github.com/City-of-Helsinki/apartment-application-service/pull/261).
This PR also includes a somewhat related fix to tests, which makes them test salesperson users better (this would have caught the bug).
> ASU-1554: Fix reservation transfer to another customer

- invoicing/pdf.py
Before this fix an empty bank name was shown as "None" in invoice PDFs.
> ASU-1496 | Fix empty bank name in invoice PDF

- Dockerfile
- docker-entrypoint.sh
Django `compilemessages` command needs to be run in the entry point script in order to get it working with the current Docker Compose config. That in turn won't work in OpenShift unless `/locale` directory is writeable by `root` group, so that needed to be changed also.
Related to [ASU-1559](https://helsinkisolutionoffice.atlassian.net/browse/ASU-1559)
> Fix translations by fixing the compilemessages command

- application_form/services/application.py
- application_form/services/export.py
- application_form/tests/test_application_api.py
- customer/services.py
Lottery result CSV report used the `has_children` field from `Customer` who owns the reservation
However, there is a flaw:
- When creating a reservation manually from Sales tool, the `reservation.has_children` is set based on `customer.has_children`
- When creating a normal application from Drupal, the `application.has_children` is ignored when creating new Customer, as a result, customers are most likely missing `has_children` value
To fix the problem:
- In the CSV, use the `reservation.has_children` instead of `customer.has_children` because it's more reliable
- Update the `create_application` logic to include `application.has_children` value when creating new customer
> ASU-1563 | Fix customer missing has_children information

- application_form/tests/test_application_api.py
Some tests failed randomly because of the new logic in create_application.
Fixed by setting the customer.has_children to True in those tests
> Fixed has_children=True in some application tests

- application_form/pdf/haso.py
Remove `aso_number` in HasoContractPDFData as it's duplicated with `right_of_residence_number`.
Change `right_of_residence_number` to use resevation right_of_residence number instead of customer.right_of_residence
> Fix right of residence number

- customer/services.py
There was a logical error when creating an application for an existed customer.
If the application.has_children is different from the current customer.has_children, Django misunderstood that this is a new customer and try to create duplicated user info.
Fixed so that Django only identifies a customer by profiles (disregarding the `customer.has_children` info). Then overwrite customer has_children info using the `application.has_children` after getting/creating the customer object
> ASU-1601 | Fix update customer data from application data

- apartment/api/sales/serializers.py
- apartment/api/serializers.py
- apartment/api/views.py
- apartment/tests/api/test_views.py
- apartment/urls.py
- application_form/api/sales/serializers.py
Implemented a couple of changes to support how reservations are fetched in the Sales UI's project detail view, because the old way of fetching them all right from the start was not feasible for production's thousands of reservations. 
* Replaced `reservations` field with `winning_reservation` and `reservation_count` fields in project detail view apartment data
* Added new API endpoint `/v1/sales/apartments/<apartment UUID>/reservations/` which returns the given apartment's all reservations sorted by list_position
> ASU-1600 | Changes to support reservation list fetching by apartment

- apartment/api/sales/serializers.py
- apartment/api/serializers.py
- apartment/utils.py
- application_form/api/serializers.py
- application_form/models/reservation.py
- application_form/services/export.py
- application_form/tests/api/test_apartment_reservation_api.py
- application_form/tests/api/test_project_reservation_view.py
- customer/tests/api/sales/test_customer_api.py
Some performance improvements to project detail API endpoint:
* tweaked application_count to not use decryption which it doesn't even need. That was very slow before.
* removed the feature that queue_position was null when lottery wasn't executed. This was causing a lot of queries, and it wasn't even needed for anything anymore
* added a bunch of prefetching to the db queries
> ASU-1604 | Project detail endpoint performance improvements

- application_form/services/queue.py
ApartmentReservation table need to be locked when getting the `list_position`, otherwise it'll return duplicated duplicated `list_position` when there are multiple application arrive at the same time.
Tested with Lotust and confirm that the solution works
> ASU-1605 | Add lock table when getting list position during creating Reservation

- .github/workflows/main.yml
- Makefile
- check-requirements-files
Make sure that the requirements*.txt files are correctly compiled from their *.in counterparts.
Add a script that checks the requirements files and hook it to CI in GitHub actions and add it also to the Makefile.
This should make it safer to merge updates to requirements.txt, since now we can be sure that the version change doesn't cause any conflicts between the package versions.
> Check requirements files in CI

- apartment_application_service/settings.py
- apartment_application_service/utils.py
- requirements-dev.in
- requirements-dev.txt
Add django-extensions to requirements-dev and add it to INSTALLED_APPS when DEBUG is enabled and the module is installed.
Most importantly (for me at least) this allows using the very useful `manage.py shell_plus` command on the local development environment.
> Enable django_extensions on DEBUG mode

- application_form/tests/utils.py
- connections/tests/utils.py
These searches were doing the search to **all** indices, which is problematic if there are several indices in the used ES instance.
This was causing tests to fail for me locally, since I had one ES index which had an apartment A0 without project_uuid and the code fails if there is no project_uuid.
> Fix couple ElasticSearch searches without index

- .github/workflows/main.yml
- application_form/validators.py
When a new application is created, the applicants are validated to make sure the same person (same date of birth and SSN suffix) hasn't already applied to the same project. This validation was painfully slow before, it took over a minute in production, because Postgres ended up decrypting all applicants in the database.
The new implementation fetches the project's all DOBs and SSN suffixes first than checks those in Python to make sure only the project's applicants are decrypted. This makes the validation a lot faster when there is a lot of data in the db.
> Fix slow project applicant validation

- .github/workflows/main.yml
- requirements-dev.in
- requirements-dev.txt
Add back the check for requirements files, but this time as a separate job so that its result can be ignored if it starts to yield problems again.
> CI: Add check-requirements job

- users/api/serializers.py
- users/tests/conftest.py
- users/tests/test_api.py
Add national_identification_number field to the profile API endpoints.
This allows API users to create Profiles with NIN and get its value with the "get details" request.
Also amend the tests and add couple new test cases.
Note: Currently NIN is not validated.
> users: Add NIN to profile API (ASU-1703)

- application_form/services/queue.py
Currently when adding a new application to an apartment that already has cancelled reservations the _shift_positions fails with the following error:
RuntimeError: This function cannot be used for adding a
reservation when the apartment has reservations without a queue_position.
This was caused because cancelled reservations have queue_position == None.
Fix the issue by filtering out the cancelled reservations.
> Fix _shift_positions for cancelled reservations

- apartment/elastic/documents.py
- apartment/tests/factories.py
- application_form/pdf/haso.py
- application_form/pdf/hitas.py
It seems that in ElasticSearch the data in the project_contract_other_terms field is not enough for the PDF, but we need to combine also data from two other fields.  Add the two other fields to ApartmentDocument and a property attribute which combines those fields with couple newlines.
Update the PDF generation code to use the combined field.
> Use project_contract_combined_terms in the PDFs

- apartment_application_service/settings.py
- apartment_application_service/tests/test_get_version.py
- apartment_application_service/version.py
Move the version getting code to its own module and use that in the settings module.
Read version first from env variables and only fall back to running Git commands.  This avoids the issue on OpenShift containers, where running the Git commands fail with an error.  Those cause false alarms to logs and the "n/a" version isn't even valid for Sentry version string, since they shouldn't contain slashes.
> Improve version getter in settings

- apartment_application_service/settings.py
- application_form/validators.py
This is useful for testing, as it allows us to create multiple applications for the same applicant.
This is not allowed in production, as it would allow an applicant to submit multiple applications for the same apartment, but there was a bug that caused multiple applications for same applicant to be created even when the validation was enabled.  Therefore we now need this setting to be able to test situations where there are multiple applications for the same applicant.
> Allow disabling applicant duplicate validation

- application_form/management/commands/fix_queue_positions_of_canceled_reservations.py
Due to a problem in the system it was possible to create duplicate applications for the same project and apartments which should not have been possible.  That situation was fixed by cancelling the duplicates before the lottery, but the lottery engine was not able to take the cancelled reservations into account, i.e. ignoring them in the lottery.
This script will fix the queues so that those reservations which were canceled before the lottery are removed from the queue.  They should have never been taken into to the lottery anyway, so it's an error that they have a queue position.
> Add management command for fixing queue positions

- application_form/management/commands/fix_queue_positions_of_canceled_reservations.py
The fix_queue_positions_of_canceled_reservations management command had an issue where it created duplicate queue numbers, because the reservations it updated in the loop were not refreshed from the database before they were used in the remove_reservation_from_queue call and that function reads the old queue position from the object.  When old queue position was used in the removal, it ended up changing queue positions incorrectly.
Fix the issue by refreshing the reservation from the database before removing it from the queue.
> queue fixer: Fix queue duplicate numbering issue

- invoicing/api/views.py
Enhance the error reporting mechanism during SAP data transmission by validating the presence of project property number in apartment installments.
Previously, the absence of property numbers would raise an error in XML generation but wouldn't be shown in the UI.
Now, missing property numbers trigger an error response in the API.
This ensures users are informed of data validation issues directly through the UI when the 'Send to SAP' button is pressed.
> Improve error handling for SAP transmissions lacking property numbers

- invoicing/tests/test_utils.py
- invoicing/utils.py
Reference number generator was giving the wrong reference number in some cases.
The condition :If the difference is 10, the checksum is 0 was missing.
> Fix reference number generator

- cost_index/tests/test_cost_index_utils.py
- cost_index/utils.py
Solved an issue in the apartment revaluation calculations where costs were incorrectly rounded down instead of up, leading to a slight undervaluation.
The end-of-date apartment price was in cases  a cent lower than the start-of-date price due to this rounding error.
Updated the calculation to ensure rounding is up.
> Fix rounding issues in revaluation calculations

- invoicing/sap/fetch/process.py
- invoicing/tests/test_process_payment_data.py
Before this update, payment synchronization with SAP would halt entirely if an invoice was not found, treating it as a critical error and preventing further updates.
This commit changes the error handling strategy: instead of raising an exception, it now logs a warning when an invoice is not found. This allows the synchronization process to continue and update the remaining payments successfully.
> Improve Payment Sync Error Handling with SAP

- application_form/services/lottery/hitas.py
When an apartment is unlinked or deleted from it's project
the room_count will be None because it is linked to that project.
Giving an error when running the lottery.
Make sure room_count is 0 when accessing it.
> Fix lottery run when apartment is unlinked from project

- apartment/services.py
When creating an offer and the right_of_occupancy_deposit was missing the value was None and then calling the _get_price_str it would return None creating an error.
Fix the function so it would return 0 when the cents is None.
> Fix create offer error

- application_form/api/sales/views.py
- invoicing/api/views.py
An error would occur when trying to download filenames that contain commas.
Remove commas from those filenames so that their Content-Disposition doesn't include commas.
> Remove commas from filenames

- invoicing/sap/fetch/process.py
- invoicing/tests/test_process_payment_data.py
Previously, the parser misread the payment value, appending an extra zero. This was due to an incorrect parsing position within the string, which has the format ie:  00062905000.
The last digit are not part of the actual amount. The first 10 are.
The parser is now adjusted to move two positions to the left, correctly extracting the payment value, with the lenght of 10 characters.
Example of a payment line
`30000001011111111111111111111111                               Xxlxkxixxx V1 00062905000  
`
column 78 is where they payment starts so (77) for the array.
> Fix parsing of line when fetching payment amount

- invoicing/utils.py
Some variables lie right_of_occupancy_payment from apartment could be None. Handle this cases when calling this method.
> Handle None in get_euros_from_cents

- cost_index/api/views.py
This field was missing in the apartment after the contract was created.
> Add end right of occupancy payment to revaluation API

- .github/workflows/main.yml
- application_form/services/reservation.py
- application_form/tests/test_lottery_hitas_services.py
When a reservation from a customer without right of residency number was added on Hitas apartments an error would occur.
Allow reservations from customers without right of residency numbers to be added on hitas apartments.
Reservations from haso apartments from users without right of residency number will still not be allowed.
> Fix bug when adding a Hitas late reservation

- cost_index/utils.py
Before the rounding was ROUND_UP which was incorrect, the correct way us ROUND_HALF_UP which will round a number to the nearest. Ei 1.055 to 1.06 and 1.054 to 1.05
> Fix rounding for revaluations

- application_form/api/sales/serializers.py
- application_form/api/serializers.py
- application_form/api/views.py
- application_form/services/application.py
- application_form/tests/conftest.py
- application_form/tests/test_application_api.py
- application_form/tests/test_sales_application_api.py
- application_form/urls.py
In order to make accesible the latest applicant's address information added the API endpoint.
Save applicantion's address to application instead of using the profile address, this change was needed when the user would delete his address from his profile making it unaccesible from the application.
> Add API for latest application's applicant

- application_form/api/views.py
Prevent error when fetching latest applicant information for users without applications by returning empty object instead so ui won't display any error.
> Remove error when user has no application

- .github/workflows/main.yml
- invoicing/api/views.py
- invoicing/pdf.py
- invoicing/sap/send/xml_utils.py
- invoicing/tests/test_api.py
- locale/fi/LC_MESSAGES/django.po
- Remove \#fuzzy markings from translation file as they disable the translated string from use
- More info: https://stackoverflow.com/a/463741
- Refactor code a bit, add type hints to `create_invoice_pdf_from_installments()`
- TODO: force Finnish language code when generating PDFs
> Add new translations for refund 1-3 and right of occupancy payment 1-3

- apartment/elastic/elastic_utils.py
Tests are run using its own ElasticSearch instance and it only has the index set with value `TEST_APARTMENT_INDEX_NAME` in `.env` file. Use this when running tests.
> Asu 1745 fix tests

- .github/workflows/main.yml
- invoicing/models.py
`ProjectInstallmentTemplate. _get_value_from_percentage(self, apartment_data)` returns default value of Decimal(0) if `"sales_price"`, `"debt_free_sales_price"` or `"right_of_occupancy_payment"` attributes on `ApartmentDocument` obj are None
> Fix KeyError when "right_of_occupancy_payment" is empty

- connections/etuovi/services.py
Previously only included apartments where `apartment_state_of_sale` was `ApartmentStateOfSale.FOR_SALE`
> Change criteria for Etuovi export. Exclude apartments where `apartment_state_of_sale` is `SOLD`
